version: '2'
services:

  db:
    image: postgres:9.4
    volumes:
      - "postgres-volume:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: template
      POSTGRES_PASSWORD: Simtlix01

  api:
    image: template:latest
    links:
        - mongo
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    volumes:
      - "mongodb-volume:/data/db"
    container_name: mongodb
    ports:  # for demo/debug purpose only
      - 27017:27017
    restart: always

volumes:
  postgres-volume:
    external: true
  mongodb-volume:
    external: true