version: '2'
services:

  db:
    image: postgres:9.4
    volumes:
      - "postgres-volume:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: template
      POSTGRES_PASSWORD: Simtlix01

  api:
    image: template:latest
    ports:
      - "8080:8080"

volumes:
  postgres-volume:
    external: true